export const ERROR_CODES = {
  // 通用
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // 认证
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  OAUTH_FAILED: 'OAUTH_FAILED',

  // 好友
  ALREADY_FRIENDS: 'ALREADY_FRIENDS',
  FRIEND_REQUEST_EXISTS: 'FRIEND_REQUEST_EXISTS',
  NOT_FRIENDS: 'NOT_FRIENDS',
  SELF_OPERATION: 'SELF_OPERATION',

  // 游戏
  ROOM_FULL: 'ROOM_FULL',
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  NOT_IN_ROOM: 'NOT_IN_ROOM',
  GAME_ALREADY_STARTED: 'GAME_ALREADY_STARTED',
  NOT_YOUR_TURN: 'NOT_YOUR_TURN',
  INVALID_MOVE: 'INVALID_MOVE',
  NOT_ENOUGH_PLAYERS: 'NOT_ENOUGH_PLAYERS',
} as const;

export const ERROR_MESSAGES: Record<string, string> = {
  UNAUTHORIZED: '请先登录',
  FORBIDDEN: '没有权限',
  NOT_FOUND: '资源不存在',
  VALIDATION_ERROR: '参数验证失败',
  INTERNAL_ERROR: '服务器内部错误',
  INVALID_TOKEN: '无效的Token',
  TOKEN_EXPIRED: 'Token已过期',
  OAUTH_FAILED: '第三方登录失败',
  ALREADY_FRIENDS: '已经是好友',
  FRIEND_REQUEST_EXISTS: '已存在好友请求',
  NOT_FRIENDS: '不是好友',
  SELF_OPERATION: '不能对自己操作',
  ROOM_FULL: '房间已满',
  ROOM_NOT_FOUND: '房间不存在',
  NOT_IN_ROOM: '不在房间中',
  GAME_ALREADY_STARTED: '游戏已经开始',
  NOT_YOUR_TURN: '还没轮到你',
  INVALID_MOVE: '无效的走法',
  NOT_ENOUGH_PLAYERS: '玩家不足',
};
